server:
  port: 8080
  http2:
    enabled: true
  address: 0.0.0.0

spring:
  profiles:
    active: default
  datasource:
    druid:
      url: 
      username: 
      password: 
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 
    password: 
    port: 
  cache:
    cache-names: redisCache
    type: redis
    redis:
      time-to-live: 5s
  aop:
    auto: true
  mvc:
    view:
      prefix: /
      suffix: .jsp
    pathmatch:
      use-suffix-pattern: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
mybatis:
  mapper-locations: ["/com/myblog/dao/*.xml"]
logging:
  level:
    root: info
  file:
    path: logs
